import json
import hashlib
from datetime import datetime, timezone
from pathlib import Path

from ml.detector import AnomalyDetector
from intelligence.rule_classifier import classify_attack_type
from storage import alert_store


ATTACK_MAPPING_FILE = (
    Path(__file__).parent / "intelligence" / "attack_mapping.json"
)

with open(ATTACK_MAPPING_FILE) as file:
    ATTACK_MAPPING = json.load(file)


_detector_instance = None


def get_anomaly_detector():
    global _detector_instance

    if _detector_instance is None:
        _detector_instance = AnomalyDetector()

    return _detector_instance


def find_attack_information(alert_type: str) -> dict:
    if alert_type in ATTACK_MAPPING:
        return ATTACK_MAPPING[alert_type]

    return {
        "technique_id": "N/A",
        "technique_name": "Unclassified Behavior",
        "tactic": "Unknown",
        "description": (
            "This anomaly does not match any known rule pattern. "
            "Manual analyst review recommended."
        ),
        "recommended_actions": [
            "Escalate to human analyst for manual classification"
        ],
        "severity_weight": 0.5,
    }


def calculate_severity(anomaly_score: float, attack_weight: float):
    combined_score = (
        (anomaly_score * 0.6)
        + (attack_weight * 0.4)
    )

    if combined_score >= 0.8:
        return "Critical", combined_score

    elif combined_score >= 0.6:
        return "High", combined_score

    elif combined_score >= 0.4:
        return "Medium", combined_score

    return "Low", combined_score


def create_timeline(device: dict, packets: list, alert_type: str):
    if not packets:
        return []

    first_timestamp = datetime.fromtimestamp(
        packets[0]["timestamp"],
        tz=timezone.utc
    )

    last_timestamp = datetime.fromtimestamp(
        packets[-1]["timestamp"],
        tz=timezone.utc
    )

    return [
        {
            "time": first_timestamp.isoformat(),
            "event": (
                f"First packet observed from "
                f"{device['device_id']}"
            ),
        },
        {
            "time": last_timestamp.isoformat(),
            "event": (
                f"Traffic window closed "
                f"({len(packets)} packets analyzed)"
            ),
        },
        {
            "time": datetime.now(timezone.utc).isoformat(),
            "event": (
                f"Anomaly detector flagged window as "
                f"'{alert_type}'"
            ),
        },
    ]


def generate_evidence(alert_id: str, packets: list):
    """
    In a real deployment, this function would save the actual
    PCAP segment to local or cloud storage and calculate the
    hash of that file.

    For this demonstration, a deterministic summary of the
    packet list is hashed to generate a verifiable SHA-256
    evidence fingerprint.
    """

    packet_summary = json.dumps(
        packets,
        sort_keys=True,
        default=str
    ).encode()

    evidence_hash = hashlib.sha256(packet_summary).hexdigest()

    return {
        "pcap_file": f"evidence/{alert_id}_capture.pcap",
        "pcap_sha256": evidence_hash,
        "chain_of_custody_id": f"COC-{alert_id}",
        "captured_by": "NetGuard AutoForensicAgent v1.0",
    }


def process_traffic_window(
    device: dict,
    packets: list,
    window_seconds: float,
    known_destinations: set = None
):
    """
    Executes the complete analysis pipeline for one traffic window.

    The traffic window is always recorded. An alert and its
    associated report information are generated only when
    the ML detector identifies the traffic as anomalous.

    Returns the alert ID when an alert is generated.
    Otherwise, returns None.
    """

    detector = get_anomaly_detector()

    analysis_result = detector.score_window(
        packets,
        window_seconds,
        known_destinations
    )

    alert_store.insert_traffic_log(
        device=device,
        features=analysis_result["features"],
        anomaly_score=analysis_result["anomaly_score"],
        is_anomaly=analysis_result["is_anomaly"],
        window_seconds=window_seconds,
    )

    if not analysis_result["is_anomaly"]:
        return None

    detected_type = classify_attack_type(
        analysis_result["features"]
    )

    attack_details = find_attack_information(
        detected_type
    )

    severity_label, severity_score = calculate_severity(
        analysis_result["anomaly_score"],
        attack_details["severity_weight"]
    )

    # Create the timeline before generating the alert.
    # The alert ID is generated by insert_alert().
    timeline_data = create_timeline(
        device,
        packets,
        detected_type
    )

    alert_id = alert_store.insert_alert(
        device=device,
        features=analysis_result["features"],
        anomaly_score=analysis_result["anomaly_score"],
        alert_type=detected_type,
        attack_info=attack_details,
        severity_label=severity_label,
        severity_score=severity_score,
        timeline=timeline_data,
        evidence={},
    )

    evidence_data = generate_evidence(
        alert_id,
        packets
    )

    alert_store._alerts.update_one(
        {"alert_id": alert_id},
        {"$set": {"evidence": evidence_data}}
    )

    return alert_id


def process_batch(batch):
    generated_alerts = []

    for item in batch:
        alert_id = process_traffic_window(
            item["device"],
            item["packets"],
            item["window_seconds"]
        )

        if alert_id:
            generated_alerts.append(alert_id)

    return generated_alerts